package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("<link href=\"assets/css/plugin/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">  \r\n");
      out.write("\r\n");
      out.write("        <!-- CSS Global -->\r\n");
      out.write("        <link href=\"assets/css/plugin/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">  \r\n");
      out.write("           \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <link href=\"assets/css/plugin/subscribe-better.css\" rel=\"stylesheet\" type=\"text/css\"> \r\n");
      out.write("\r\n");
      out.write("        <!-- Custom CSS -->\r\n");
      out.write("        <link href=\"assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("        <!-- Color CSS --> \r\n");
      out.write("\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"assets/js/plugin/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"assets/js/plugin/respond.js\"></script>\r\n");
      out.write("        <![endif]--> \r\n");
      out.write("         \r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("\t\t.login{\r\n");
      out.write("\t\t\twidth:400px;\r\n");
      out.write("\t\t\theight:300px;\r\n");
      out.write("\t\t\tbackground:url(img/subscribe.jpg)no-repeat;\r\n");
      out.write("\t\t\tposition:absolute;\r\n");
      out.write("\t\t\tmargin-top:-1200px;\r\n");
      out.write("\t\t\tmargin-left:550px;\r\n");
      out.write("\t\t\tborder-top-right-radius:20px;\r\n");
      out.write("\t\t\tborder-top-left-radius:20px;\r\n");
      out.write("\t\t\tborder-bottom-right-radius:20px;\r\n");
      out.write("\t\t\tborder-bottom-left-radius:20px;\r\n");
      out.write("\t\t\tdisplay:none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t.top{\r\n");
      out.write("\t\t\twidth:400px;\r\n");
      out.write("\t\t\theight:50px;\r\n");
      out.write("\t\t\tfont-size:24px;\r\n");
      out.write("\t\t\tfont-family:\"幼圆\";\r\n");
      out.write("\t\t\tborder-top-right-radius:20px;\r\n");
      out.write("\t\t\tborder-top-left-radius:20px;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t.close{\r\n");
      out.write("\t\t\ttext-align:right;\r\n");
      out.write("\t\t\tpadding-right:20px;\r\n");
      out.write("\t\t\tline-height:70px;\r\n");
      out.write("\t\t\tfont-weight:bold;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t.tip{\r\n");
      out.write("\t\t\tpadding-left:140px;\r\n");
      out.write("\t\t\tline-height:70px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t.menu{\r\n");
      out.write("\t\t\twidth:95%;\r\n");
      out.write("\t\t\theight:220px;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmargin:0px auto;\r\n");
      out.write("\t\t\tmargin-top:20px;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.t{\r\n");
      out.write("\t\t\t\tfont-size:10px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t.denglu{\r\n");
      out.write("\t\t\twidth:150px;\r\n");
      out.write("\t\t\theight:40px;\r\n");
      out.write("\t\t\tborder-top-right-radius:20px;\r\n");
      out.write("\t\t\tborder-top-left-radius:20px;\r\n");
      out.write("\t\t\tborder-bottom-right-radius:20px;\r\n");
      out.write("\t\t\tborder-bottom-left-radius:20px;\r\n");
      out.write("\t\t\tborder:0px;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        function onload(){\r\n");
      out.write("\t\tvar msg=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\tvar rows = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rows}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\tif(msg.length>0){\r\n");
      out.write("\t\t\talert(msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(rows>0){\r\n");
      out.write("\t\t\talert('注册成功！');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\tfunction show(){\r\n");
      out.write("\t\t\tdocument.getElementById(\"login\").style.display=\"block\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction lclose(){\r\n");
      out.write("\t\t\tdocument.getElementById(\"login\").style.display=\"none\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tfunction show1(){\r\n");
      out.write("\t\t\tdocument.getElementById(\"add\").style.display=\"block\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction lclose1(){\r\n");
      out.write("\t\t\tdocument.getElementById(\"add\").style.display=\"none\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("    function focusByUsername(){\r\n");
      out.write("\t\tdocument.getElementById(\"username\").value=\"\";\r\n");
      out.write("\t\tdocument.getElementById(\"resultUsername\").innerHTML=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction focusByPassword(){\r\n");
      out.write("\t\tdocument.getElementById(\"password\").value=\"\";\r\n");
      out.write("\t\tdocument.getElementById(\"resultPassword\").innerHTML=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction focusByReqCode(){\r\n");
      out.write("\t\tdocument.getElementById(\"reqCode\").value=\"\";\r\n");
      out.write("\t\tdocument.getElementById(\"resultReqCode\").innerHTML=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction blurByUsername(){\r\n");
      out.write("\t\tvar uname=document.getElementById(\"username\").value;\r\n");
      out.write("\t\tif(uname==\"\"){\r\n");
      out.write("\t\tdocument.getElementById(\"resultUsername\").innerHTML=\"请输入用户名\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(uname.length>10){\r\n");
      out.write("\t\t\tdocument.getElementById(\"resultUsername\").innerHTML=\"用户名不能大于10位\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"username\").value=\"\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementById(\"resultUsername\").innerHTML=\"OK\";\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction blurByPassword(){\r\n");
      out.write("\t\tvar pwd=document.getElementById(\"password\").value;\r\n");
      out.write("\t\tif(pwd==\"\"){\r\n");
      out.write("\t\tdocument.getElementById(\"resultPassword\").innerHTML=\"请输入密码\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(pwd.length>10){\r\n");
      out.write("\t\t\tdocument.getElementById(\"resultPassword\").innerHTML=\"密码不能大于10位\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"password\").value=\"\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementById(\"resultPassword\").innerHTML=\"OK\";\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction blurByReqCode(){\r\n");
      out.write("\t\tvar reqCode=document.getElementById(\"reqCode\").value;\r\n");
      out.write("\t\tif(reqCode==\"\"){\r\n");
      out.write("\t\tdocument.getElementById(\"resultReqCode\").innerHTML=\"请输入验证码\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(reqCode.length>4){\r\n");
      out.write("\t\t\tdocument.getElementById(\"resultReqCode\").innerHTML=\"验证码不能大于4位\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"reqCode\").value=\"\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementById(\"resultReqCode\").innerHTML=\"OK\";\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t<!--注册-->\r\n");
      out.write("\t  \r\n");
      out.write("\t  function blurByUsername1(){\r\n");
      out.write("\t\t   var username=document.getElementById(\"username1\").value;\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t   if(username==\"\"){\r\n");
      out.write("\t\t\t   document.getElementById(\"resultUsername1\").innerHTML=\"用户名不能为空！\";\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   if(username.length>10){\r\n");
      out.write("\t\t\t   document.getElementById(\"resultUsername1\").innerHTML=\"输入的用户名为10位之内！\";\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }else{\r\n");
      out.write("\t\t\t   document.getElementById( \"resultUsername1\").innerHTML=\"此用户名可用！\"; \r\n");
      out.write("\t\t\t   return true;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  function blurByPassword1(){\r\n");
      out.write("\t\t   var password1=document.getElementById(\"password1\").value;\r\n");
      out.write("\t\t   if(password1==\"\"){\r\n");
      out.write("\t\t\t   document.getElementById(\"resultPassword1\").innerHTML=\"密码名不能为空！\";\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   if(password1.length>10){\r\n");
      out.write("\t\t\t   document.getElementById(\"resultPassword1\").innerHTML=\"输入的密码名为10位之内！\";\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }else{\r\n");
      out.write("\t\t\t   document.getElementById( \"resultPassword1\").innerHTML=\"此密码名可用！\";  \r\n");
      out.write("\t\t\t   return true;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t  }\r\n");
      out.write("\t \r\n");
      out.write("\t  function blurByPassword2(){\r\n");
      out.write("\t\t   var password1=document.getElementById(\"password1\").value;\r\n");
      out.write("\t\t   var password2=document.getElementById(\"password2\").value;\r\n");
      out.write("\t\t   if(password2==\"\"){\r\n");
      out.write("\t\t\t   document.getElementById(\"resultPassword2\").innerHTML=\"确定密码名不能为空！\";\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   if(password2.length>10){\r\n");
      out.write("\t\t\t   document.getElementById(\"resultPassword2\").innerHTML=\"输入的密码名为10位之内！\";\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }else if(password2!=password1){\r\n");
      out.write("\t\t\t     document.getElementById(\"resultPassword2\").innerHTML=\"密码输入错误！\";\r\n");
      out.write("\t\t\t      return false\r\n");
      out.write("\t\t\t   }else{\r\n");
      out.write("\t\t\t   document.getElementById( \"resultPassword2\").innerHTML=\"此用户密码正确！\";  \r\n");
      out.write("\t\t\t   return true;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  function blurByNickname(){\r\n");
      out.write("\t\t   var nickname=document.getElementById(\"nickname\").value;\r\n");
      out.write("\t\t   if(nickname==\"\"){\r\n");
      out.write("\t\t\t   document.getElementById(\"resultNickname\").innerHTML=\"用户昵称名不能为空！\";\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   if(nickname.length>10){\r\n");
      out.write("\t\t\t   document.getElementById(\"resultNickname\").innerHTML=\"输入的用户昵称名为10位之内！\";\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }else{\r\n");
      out.write("\t\t\t   document.getElementById( \"resultNickname\").innerHTML=\"此用户昵称名可用！\";  \r\n");
      out.write("\t\t\t   return true;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  function focusByUsername1(){\r\n");
      out.write("\t\t   document.getElementById( \"username1\").value=\"\";\r\n");
      out.write("\t\t   document.getElementById( \"resultUsername1\").innerHTML=\"\"; \r\n");
      out.write("\t  }\r\n");
      out.write("\t  function focusPassword1(){\r\n");
      out.write("\t\t   document.getElementById( \"password1\").value=\"\";\r\n");
      out.write("\t\t   document.getElementById( \"resultPassword1\").innerHTML=\"\"; \r\n");
      out.write("\t\t  \r\n");
      out.write("\t  }\r\n");
      out.write("\t  function focusPassword2(){\r\n");
      out.write("\t\t   document.getElementById( \"password2\").value=\"\";\r\n");
      out.write("\t\t   document.getElementById( \"resultPassword2\").innerHTML=\"\"; \r\n");
      out.write("\t\t  \r\n");
      out.write("\t  }\r\n");
      out.write("\t  function focusNickname(){\r\n");
      out.write("\t\t    document.getElementById( \"nickname\").value=\"\";\r\n");
      out.write("\t\t   document.getElementById( \"resultNickname\").innerHTML=\"\";\r\n");
      out.write("\t\t  \r\n");
      out.write("\t  }\r\n");
      out.write("\t  function login(){\r\n");
      out.write("\t\tif(blurByUsername()&&blurByPassword()&&blurByReqCode()){\r\n");
      out.write("\t\t\tdocument.getElementById(\"loginForm\").action=\"doLogin.action\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t  function addUser(){\r\n");
      out.write("\t\t  if(blurByUsername1()&&blurByPassword1()&&blurByPassword2()&& blurByNickname()){\r\n");
      out.write("\t\t    document.getElementById(\"addForm\").action=\"doAddUser.action\";\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t  }else{\r\n");
      out.write("\t\t\t  return false;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t    \r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/jquery-1.5.2.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \t\t<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/login.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write(" <body id=\"home\" class=\"wide\" onLoad=\"onload();\">\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("        <div id=\"loading\">\r\n");
      out.write("            <div class=\"loader\">\r\n");
      out.write("                <div class=\"dot\"></div>\r\n");
      out.write("                <div class=\"dot\"></div>\r\n");
      out.write("                <div class=\"dot\"></div>\r\n");
      out.write("                <div class=\"dot\"></div>\r\n");
      out.write("                <div class=\"dot\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- WRAPPER -->\r\n");
      out.write("        <main class=\"wrapper home-wrap\"> \r\n");
      out.write("            <!-- CONTENT AREA -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Main Header Start 头部导航栏 -->\r\n");
      out.write("            <header class=\"main-header\">                  \r\n");
      out.write("                <div class=\"container-fluid rel-div\">\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-8\">\r\n");
      out.write("                        <div class=\"main-logo\">\r\n");
      out.write("                            <a href=\"javascript:void(0);\"> <strong>mzjw<img src=\"assets/img/icons/logo-icon.png\" alt=\"\" /> </strong> <span class=\"light-font\">farmfood</span>  </a>\r\n");
      out.write("                            <span class=\"medium-font\">ORGANIC STORE</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-6 responsive-menu\">  \r\n");
      out.write("                        <div class=\"responsive-toggle fa fa-bars\"> </div>\r\n");
      out.write("                        <nav class=\"fix-navbar\" id=\"primary-navigation\">            \r\n");
      out.write("                            <ul class=\"primary-navbar\">                                                \r\n");
      out.write("                                <li><a href=\"javascript:void(0);\"> Home</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:void(0);\" onClick=\"show();\">登录</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\" onClick=\"show1();\">注册</a></li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\">帮助</a></li>        \r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:void(0);\">开发者人员</a></li>\r\n");
      out.write("                            </ul>                           \r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("         \r\n");
      out.write("            </header>\r\n");
      out.write("            <!-- / Main Header Ends头部导航栏结束 -->   \r\n");
      out.write("\r\n");
      out.write("            <!-- Main Slider Start 主界面 -->\r\n");
      out.write("            <section class=\"main-slide\">\r\n");
      out.write("                <img alt=\"..\" src=\"assets/img/slider/slide-1.jpg\" />\r\n");
      out.write("                <div class=\"tbl-wrp slide-1\">\r\n");
      out.write("                    <div class=\"text-middle\">\r\n");
      out.write("                        <div class=\"tbl-cell\">\r\n");
      out.write("                            <div class=\"slide-caption container text-center\">\r\n");
      out.write("                                <div class=\"slide-title\">\r\n");
      out.write("                                    <img src=\"assets/img/icons/slide-txt-1.png\" alt=\"\" />\r\n");
      out.write("                                    <span>100% Guarantee</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"slide-title2 pb-50\">\r\n");
      out.write("                                    <h2 class=\"section-title\"> <span class=\"light-font\">Live </span> <strong>organic </strong> <span class=\"light-font\">for live </span> <strong>healthy </strong> </h2>\r\n");
      out.write("                                    <h4 class=\"sub-title\"> ORGANIC FRUITS, VEGETABLES, AND LOT MORE TO YOUR DOOR </h4>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"slide\">\r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- / Main Slider Ends主界面结束 -->   \r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("            \r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("            <!-- / CONTENT AREA -->\r\n");
      out.write("\r\n");
      out.write("            <!-- FOOTER尾部界面 -->\r\n");
      out.write("            <footer class=\"page-footer\"> \r\n");
      out.write("                <section class=\"sec-space light-bg\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-3 col-sm-12 footer-widget\">\r\n");
      out.write("                                <div class=\"main-logo\">\r\n");
      out.write("                                    <a> <strong>mzjw<img src=\"assets/img/icons/logo-icon.png\" alt=\"\" /> </strong> <span class=\"light-font\">farmfood</span>  </a>\r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"text-widget\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3 col-sm-4 footer-widget\">\r\n");
      out.write("                                <h2 class=\"title-1\"> <strong>开发人员 </strong> </h2>\r\n");
      out.write("                                <span class=\"divider-2\"></span>\r\n");
      out.write("                                <ul class=\"list\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    <li> <a>景凡</a> </li>\r\n");
      out.write("                                   \r\n");
      out.write("                                    \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3 col-sm-4 footer-widget\">\r\n");
      out.write("                                <h2 class=\"title-1\"><strong>E-mail</strong> </h2>\r\n");
      out.write("                                <span class=\"divider-2\"></span>\r\n");
      out.write("                                <ul class=\"list\">\r\n");
      out.write("                                   \r\n");
      out.write("                                    <li><a>609987416@qq.com</a></li>\r\n");
      out.write("                                    \r\n");
      out.write("                                   \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"footer-bottom\">\r\n");
      out.write("                    <div class=\"pattern\"> \r\n");
      out.write("                        <img alt=\"\" src=\"assets/img/icons/white-pattern.png\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"to-top\" class=\"to-top\"> <i class=\"fa fa-arrow-circle-o-up\"></i> </div>\r\n");
      out.write("                    <div class=\"container ptb-50\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            \r\n");
      out.write("                </section>\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- /FOOTER尾部界面结束 -->\r\n");
      out.write("           \r\n");
      out.write("        \r\n");
      out.write("\t\t<!--页面弹出登录框-->\r\n");
      out.write("        <div class=\"login\" id=\"login\">\r\n");
      out.write("        <div class=\"top\"><span class=\"tip\">登 录 窗 口</span><span class=\"close\" onClick=\"lclose();\">×</span></div>\r\n");
      out.write("        <hr/>\r\n");
      out.write("        <div class=\"menu\">\r\n");
      out.write("        <form id=\"loginForm\" action =\"\" method=\"post\" onSubmit=\"login();\">\r\n");
      out.write("        <table border=\"0\" width=\"100%\" height=\"220px;\">\r\n");
      out.write("        <tr>\r\n");
      out.write("        \t<td width=\"30%\" align=\"right\">用户名：</td>\r\n");
      out.write("            <td width=\"30%\"><input onBlur=\"blurByUsername();\" onFocus=\"focusByUsername();\" type=\"text\" name=\"username\" id=\"username\"/></td>\r\n");
      out.write("            <td class=\"t\" width=\"30%\" align=\"left\" id=\"resultUsername\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("       \t    <td width=\"30%\" align=\"right\">密码：</td>\r\n");
      out.write("            <td width=\"30%\"><input onBlur=\"blurByPassword();\" onFocus=\"focusByPassword();\" type=\"password\" name=\"password\" id=\"password\"/></td>\r\n");
      out.write("            <td class=\"t\" width=\"30%\" align=\"left\" id=\"resultPassword\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("       \t    <td width=\"30%\" align=\"right\" >验证码：</td>\r\n");
      out.write("            <td width=\"30%\"><input onBlur=\"blurByReqCode();\" onFocus=\"focusByReqCode()\" type=\"text\" name=\"reqCode\" id=\"reqCode\"/></td>\r\n");
      out.write("            <td class=\"t\" id=\"resultReqCode\" ></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td  colspan=\"3\" align=\"center\"><img src=\"vcode.jsp\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("        \t<td colspan=\"3\" align=\"center\"><input class=\"denglu\" type=\"submit\" value=\"登 录\"/></td>\r\n");
      out.write("            \r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        </table>\r\n");
      out.write("        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("\t\t<!--页面弹出注册框-->\r\n");
      out.write("        <div class=\"login\" id=\"add\">\r\n");
      out.write("        <div class=\"top\"><span class=\"tip\">注 册 窗 口</span><span class=\"close\" onClick=\"lclose1();\">×</span></div>\r\n");
      out.write("        <hr/>\r\n");
      out.write("        <div class=\"menu\">\r\n");
      out.write("        <form id=\"addForm\" action =\"\" method=\"post\" onSubmit=\"return addUser();\">\r\n");
      out.write("        <table border=\"0\" width=\"100%\" height=\"220px;\">\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td width=\"30%\"  align=\"right\" >用户名：</td>\r\n");
      out.write("      <td align=\"left\" width=\"20%\">\r\n");
      out.write("         <input onkeyup=\"value=value.replace(/[^\\w\\.\\/]/ig,'')\" id=\"username1\" onfocus=\"focusByUsername1();\" onblur=\"blurByUsername1();\" type=\"text\" name=\"username1\" style=\"width:150px\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td class=\"t\" id=\"resultUsername1\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td width=\"20%\" align=\"right\">密码：</td>\r\n");
      out.write("      <td align=\"left\">\r\n");
      out.write("       <input  onkeyup=\"value=value.replace(/[^\\w\\.\\/]/ig,'')\" id=\"password1\" onfocus=\"focusPassword1();\" onblur=\"blurByPassword1();\" type=\"password\" name=\"password1\" style=\"width:150px\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td class=\"t\" id=\"resultPassword1\"></td>\r\n");
      out.write("     \r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td width=\"20%\" align=\"right\">确认密码：</td>\r\n");
      out.write("      <td align=\"left\">\r\n");
      out.write("       <input  onkeyup=\"value=value.replace(/[^\\w\\.\\/]/ig,'')\" id=\"password2\" onfocus=\"focusPassword2();\" onblur=\"blurByPassword2();\" type=\"password\" name=\"password2\" style=\"width: 150px\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td class=\"t\" id=\"resultPassword2\"></td>\r\n");
      out.write("     \r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td width=\"20%\" align=\"right\">用户昵称：</td>\r\n");
      out.write("      <td align=\"left\">\r\n");
      out.write("        <input id=\"nickname\" onfocus=\"focusNickname();\" onblur=\"blurByNickname();\" type=\"text\" name=\"nickname\" style=\"width: 150px\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td class=\"t\" id=\"resultNickname\"></td>\r\n");
      out.write("     \r\n");
      out.write("     </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        \t<td colspan=\"3\" align=\"center\">\r\n");
      out.write("        \t\t<input class=\"denglu\" type=\"submit\" value=\"注册\"/>\r\n");
      out.write("        \t</td>\r\n");
      out.write("            \r\n");
      out.write("      </tr>\r\n");
      out.write("         \r\n");
      out.write("        </table>\r\n");
      out.write("        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 页面弹出登陆框结束 -->\r\n");
      out.write("\r\n");
      out.write("        <!-- JS Global -->\r\n");
      out.write("        <script src=\"assets/js/plugin/jquery-2.2.4.min.js\"></script>   \r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("        <script src=\"assets/js/plugin/jquery.subscribe-better.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- Custom JS -->   \r\n");
      out.write("        <script src=\"assets/js/theme.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
